"""encodings

Revision ID: 11533c5f4ead
Revises: 6220d4684f42
Create Date: 2016-10-21 10:38:04.195481

"""

# revision identifiers, used by Alembic.
revision = '11533c5f4ead'
down_revision = '6220d4684f42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('msg_encodings', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'msg_encodings')
    ### end Alembic commands ###
