"""method

Revision ID: 5734f9a60a02
Revises: 87f0033732e3
Create Date: 2016-10-21 15:57:53.266557

"""

# revision identifiers, used by Alembic.
revision = '5734f9a60a02'
down_revision = '87f0033732e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('method_inquire', sa.String(length=10), nullable=False))
    op.add_column('provider', sa.Column('method_status', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'method_status')
    op.drop_column('provider', 'method_inquire')
    ### end Alembic commands ###
