"""param

Revision ID: 60fd1f399d75
Revises: c47ffa348b6f
Create Date: 2016-10-24 10:18:00.091722

"""

# revision identifiers, used by Alembic.
revision = '60fd1f399d75'
down_revision = 'c47ffa348b6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('param_inquire', sa.String(length=10), nullable=False))
    op.add_column('provider', sa.Column('param_kwargs_status', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'param_kwargs_status')
    op.drop_column('provider', 'param_inquire')
    ### end Alembic commands ###
