"""json

Revision ID: 6220d4684f42
Revises: 3bf410c3a395
Create Date: 2016-10-21 10:00:18.485643

"""

# revision identifiers, used by Alembic.
revision = '6220d4684f42'
down_revision = '3bf410c3a395'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('param_kwargs', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'param_kwargs')
    ### end Alembic commands ###
