"""sms

Revision ID: 6db923298ea7
Revises: ac1894fc578e
Create Date: 2016-10-24 11:55:08.172985

"""

# revision identifiers, used by Alembic.
revision = '6db923298ea7'
down_revision = 'ac1894fc578e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms', sa.Column('modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms', 'modified')
    ### end Alembic commands ###
