"""path

Revision ID: 87f0033732e3
Revises: a98d24bd5950
Create Date: 2016-10-21 14:54:27.093004

"""

# revision identifiers, used by Alembic.
revision = '87f0033732e3'
down_revision = 'a98d24bd5950'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('path_inquire', sa.String(length=10), nullable=False))
    op.add_column('provider', sa.Column('path_send', sa.String(length=10), nullable=False))
    op.add_column('provider', sa.Column('path_status', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'path_status')
    op.drop_column('provider', 'path_send')
    op.drop_column('provider', 'path_inquire')
    ### end Alembic commands ###
