"""add_base_model

Revision ID: b429a60a4b0f
Revises: d805861cf17d
Create Date: 2016-10-24 12:18:39.301856

"""

# revision identifiers, used by Alembic.
revision = 'b429a60a4b0f'
down_revision = 'd805861cf17d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_record', sa.Column('modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_record', 'modified')
    ### end Alembic commands ###
