"""type

Revision ID: c47ffa348b6f
Revises: 938b64b8545d
Create Date: 2016-10-24 09:22:14.649147

"""

# revision identifiers, used by Alembic.
revision = 'c47ffa348b6f'
down_revision = '938b64b8545d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms', sa.Column('type', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms', 'type')
    ### end Alembic commands ###
