"""provider

Revision ID: d805861cf17d
Revises: 6db923298ea7
Create Date: 2016-10-24 12:15:51.548404

"""

# revision identifiers, used by Alembic.
revision = 'd805861cf17d'
down_revision = '6db923298ea7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'modified')
    ### end Alembic commands ###
